# Generated by Django 5.0.2 on 2024-02-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acceptClient", models.BooleanField(default=False)),
                ("description", models.TextField(max_length=500)),
                ("initial_date", models.DateField()),
                ("fin_date", models.DateField()),
                ("cost", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Ne", "Negociacion"),
                            ("Ac", "Aceptado"),
                            ("En", "En proceso"),
                            ("Fi", "Finalizado"),
                            ("Ca", "Cancelado"),
                            ("Pa", "Pagado"),
                        ],
                        default="Ne",
                        max_length=2,
                    ),
                ),
                (
                    "acceptWorker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptWorker",
                        to="user.user",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="user.user",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
