# Generated by Django 5.0.2 on 2024-02-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="acceptWorker",
            field=models.BooleanField(default=False),
        ),
    ]
