# Generated by Django 5.0.2 on 2024-03-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contract_acceptworker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
