# Generated by Django 5.0.2 on 2024-02-28 15:18

import django.core.validators
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', service.models.EnumField(choices=[(1, 'Lavandero'), (2, 'Celador'), (3, 'Albañil')])),
                ('city', models.TextField()),
                ('experience', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StringIntegerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
