# Generated by Django 5.0.2 on 2024-02-29 10:51

import django.core.validators
import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', service.models.EnumField(choices=[(1, 'Lavandero'), (2, 'Celador'), (3, 'Albañil')])),
                ('city', models.TextField()),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0),
                django.core.validators.MaxValueValidator(80)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='user.user')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_price', models.PositiveIntegerField()),
                ('service', models.ForeignKey(default=None, null=True,
                on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
