# Generated by Django 5.0.2 on 2024-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='profession',
            field=models.IntegerField(choices=[(1, 'Lavandero'), (2, 'Celador'), (3, 'Albañil')]),
        ),
    ]
