# Generated by Django 5.0.2 on 2024-02-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
