# Generated by Django 5.0.2 on 2024-02-28 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(80.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
