# Generated by Django 5.0.2 on 2024-03-06 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_service_profession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "job", "verbose_name_plural": "jobs"},
        ),
        migrations.AlterField(
            model_name="job",
            name="estimated_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Introduzca el coste en euros",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
