# Generated by Django 5.0.2 on 2024-02-28 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_work_alter_service_options_service_works'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='works',
            new_name='jobs',
        ),
        migrations.AlterField(
            model_name='service',
            name='experience',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
