# Generated by Django 5.0.2 on 2024-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_job_estimated_price_alter_service_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_promoted",
            field=models.DateField(default="2000-02-02"),
        ),
    ]
