# Generated by Django 5.0.2 on 2024-02-24 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('desc', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('lenguage', models.CharField(blank=True, max_length=50, null=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
