# Generated by Django 5.0.2 on 2024-03-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0002_rename_lenguage_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_worker', models.BooleanField(default=False)),
                ('accept_client', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
                ('initial_date', models.DateField()),
                ('fin_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('state', models.CharField(choices=[('Ne', 'Negociacion'), ('Ac', 'Aceptado'), ('En', 'En proceso'), ('Fi', 'Finalizado'), ('Ca', 'Cancelado'), ('Pa', 'Pagado')], default='Ne', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='user.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='user.user')),
            ],
        ),
    ]
