# Generated by Django 5.0.2 on 2024-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.FloatField(),
        ),
    ]
