# Generated by Django 5.0.2 on 2024-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_date',
            field=models.DateTimeField(),
        ),
    ]
