# Generated by Django 5.0.2 on 2024-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_cost_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description_cancelation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
