# Generated by Django 5.0.2 on 2024-03-17 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_cost_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='cost',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Introduzca el coste en euros', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('complete', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
        ),
    ]
