# Generated by Django 5.0.2 on 2024-03-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contract_cost_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
